# http port number(default 8080)
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# db connection(oracle) - spring(context.xml)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_ict03?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql


# spring(servlet-context.xml)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
     
  jpa:       
    hibernate:
      ddl-auto: update # create, update, none #create: 사용자 테이블 없으면 자동생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  application:     
    name: user-service
  main: 
    allow-bean-definition-overriding: true 

# MyBatis - spring(dataSource-config.xml)
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: react.oracle.ict03.dao
   
